### ISSUE TITLE
bug: dead lock when execute queries

### ISSUE THREAD

**Issue by ShannonBase** [Shannon-Data/ShannonBase#171]
### Search before asking

- [X] I had searched in the [issues](https://github.com/Shannon-Data/ShannonBase/issues) and found no similar issues.

### Version

ver0.2.0-beta

### What's Wrong?

session 1: 
alter table tt secondary_load;

session2 :
insert into tt values(xxxx);  batch insertion.

then in session 1: execute select statement, a dead lock occurs. 

when pop the changes into rapid, and now, executing some queries on rapid. it could occur deadlock.

### How to Reproduce?

1: session1:
 CALL insert_into_tt1(); //trying to insert 1000rows into a table.

2: session2:
select count(1) from tt1;

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by RingsC** [comment]
It's not a deadlock.
the root cause is here: need to imp the `records` function to get the real rows count of a rapid table.

**Comment by RingsC** [comment]
It's not a deadlock.
the root cause is here: need to imp the `records` function to get the real rows count of a rapid table.
