### ISSUE TITLE
Feature: add new mtr_log_t for pop thread

### ISSUE THREAD

**Issue by ShannonBase** [Shannon-Data/ShannonBase#175]
**Summary**
Now that, we parse all the mlog records, but we should just care about three type operations: (1) insert; (2) delete; (3) update. 
Besides, the other operations is not our concern. Taking `create database` or `drop database` as examples, all the mlog records generate in these operations should not be added into `sys_pop_buff`. 

A new type `MTR_LOG_WITH_POP` is added, if the mlog is not this type, we do not add these mlogs into pop buff, otherwise, these mlogs are added.

**Comment by ShannonBase** [comment]
```
/** Logging modes for a mini-transaction */
enum mtr_log_t {
  /** Default mode: log all operations modifying disk-based data */
  MTR_LOG_ALL = 0,

  /** Log no operations and dirty pages are not added to the flush list */
  MTR_LOG_NONE = 1,

  /** Don't generate REDO log but add dirty pages to flush list */
  MTR_LOG_NO_REDO = 2,

  /** Inserts are logged in a shorter form */
  MTR_LOG_SHORT_INSERTS = 3,

  /** Last element */
  MTR_LOG_MODE_MAX = 4
};
```
a new type of log mode is added to indicate that should we route the mlog records to pop buffer too or not.

**Comment by ShannonBase** [comment]
or another approach is adding a member field in `mtr` to indicates whether the mlog should be added or not.
```
/** Mini-transaction handle and buffer */
struct mtr_t {
  /** State variables of the mtr */
  struct Impl {
    /** memo stack for locks etc. */
    mtr_buf_t m_memo;

    /** mini-transaction log */
    mtr_buf_t m_log;

    /** true if inside ibuf changes */
    bool m_inside_ibuf;

    /** true if the mini-transaction might have modified buffer pool pages */
    bool m_modifications;

    bool m_to_pop;
```

**Comment by RingsC** [comment]
approach 3: use `SQLCOM_INSERT`, `SQLCOM_DELETE`, `SQLCOM_UPDATE` to determine that should we route the redo log to pop or not..
