### ISSUE TITLE
Feature: process mlog of loaded table 

### ISSUE THREAD

**Issue by ShannonBase** [Shannon-Data/ShannonBase#183]
**Summary**

adding a new condtion to decide whether the changes should be poped or not.
```
    case SQLCOM_REPLACE_SELECT:
     case SQLCOM_INSERT:
     case SQLCOM_UPDATE:
-    case SQLCOM_DELETE:
-        prebuilt->m_to_pop_buff = true;
+    case SQLCOM_DELETE: {
+      prebuilt->m_to_pop_buff =
+        ShannonBase::shannon_loaded_tables->get(table->s->db.str,
+                     table->s->table_name.str) ? true : false;
+    }break;

```

**Comment by RingsC** [comment]
If a table laoded into rapid, now, shannon will launch a pop thread to dealing with the changes. Now, it will route all changes to pop buffer, but these changes donot belong to loaded tables. That's why we add a new cond to check these  changes.
