### ISSUE TITLE
feat(shannon): Vector Engine

### ISSUE THREAD

**Issue by RingsC** [Shannon-Data/ShannonBase#33]
To build up the vector engine for shannonbase. The native idea just like the innodb does.  Nowdays, the vector processing ability becomes the foundmental ability for LLM. In PostgreSQL, it has a plugin, pg_vector to process vector data. But, in mysql, we dont have this.

Therefore, we want to build a vector engine to process vector data. Taking the following as an instance, 
```
create table tb1(col1 int, col2 vector(10)) engine=vector.  
```
or vector data type.
ref: 
https://github.com/facebookresearch/faiss

**Comment by ShannonBase** [comment]
for vector data type:  ref: [oracle vector data type](https://docs.oracle.com/en/database/oracle/oracle-database/23/vecse/create-tables-using-vector-data-type.html)

**Comment by ShannonBase** [comment]
Now, supported in 9.0. 
```
Added support for the VECTOR data type that was introduced in MySQL Enterprise Server 9.0.0. (WL #16171)
```
