### ISSUE TITLE
feat(shannon): Upgrade to 8.4.x

### ISSUE THREAD

**Issue by ShannonBase** [Shannon-Data/ShannonBase#78]
The base code line is 8.1.x, but the latest version is 8.4.x. and a lot of enhancements are added, and securities improvements added. Therefore, we shoul upgrade to 8.4.x to keep pace with community version.

**Comment by RingsC** [comment]
Now, 8.4.0 LTS is eanbled, therefore, we should upgrade the code base of ShannonBase from 8.1.0 to 8.4.0 LTS.

**Comment by RingsC** [comment]
using v8.4 as the core of ShannonBase LTS.

**Comment by hustjieke** [comment]
Base tag: mysql-cluster v8.4.2
